USE `classicmodels`;
#Agrupar por nome do departmento e mostrar a soma salarial de cada
SELECT DEPARTMENT_NAME, JOB_TITLE AS 'Cargo', COUNT(EMPLOYEE_ID) AS 'Quantidade de funcionários'
FROM EMPLOYEES EM INNER JOIN DEPARTMENTS DE ON EM.DEPARTMENT_ID = DE.DEPARTMENT_ID
INNER JOIN JOBS JB ON EM.JOB_ID = JB.JOBS_ID
GROUP BY DEPARTMENT_NAME, JOB_TITLE;

##CASE SQL
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE,
CASE (2022 - YEAR(HIRE_DATE))
	WHEN  1 THEN ' 1 ANO DE EMPRESA'
    WHEN  3 THEN ' 3 ANOS DE EMPRESA'
    WHEN  5 THEN ' 5 ANOS DE EMPRESA'
    WHEN 10 THEN '10 ANOS DE EMPRESA'
    WHEN 20 THEN '20 ANOS DE EMPRESA'
    ELSE 'MAIS DE 20 ANOS'
    END ANIVERSARIO
FROM EMPLOYEES
ORDER BY ANIVERSARIO DESC;

SELECT FIRST_NAME, LAST_NAME, SALARY, 
CASE 
	WHEN SALARY < 1500 THEN Baixo
    WHEN SALARY >=1500 AND SALARY < 3000 THEN 'Média'
    WHEN SALARY >= 3000 THEN 'Alto'
    END AVALIACAO_SALARIAL
    FROM EMPLOYEES 
    